-- Create Add_Members table
CREATE TABLE MEMBERS( 
    MEMBER_ID       INTEGER,
    MEMBER_NAME     VARCHAR(200),
    MEMBER_SURNAME  VARCHAR(250),
    MEMBER_PASSWORD VARCHAR(500),
    MEMBER_ROLE     VARCHAR(500),
    PRIMARY KEY(MEMBER_ID)
);

CREATE TABLE BOOKS( 
    BOOK_ID   INTEGER,
    BOOK_NAME VARCHAR(200),
    GENRE     VARCHAR(500),
    AUTHOR    VARCHAR(500),
    PRIMARY KEY(BOOK_ID)
);

CREATE TABLE BORROW_BOOK( 
    BORROW_ID INTEGER,
    BOOK_ID   INTEGER,
    MEMBER_ID INTEGER,
    BOOK_NAME VARCHAR(200),
	MEMBER_NAME  VARCHAR(200),
    BORROW_DATE  DATE,
    PRIMARY KEY(BORROW_ID)
);

CREATE TABLE RETURN_BOOK( 
    RETURN_ID INTEGER,
    BOOK_ID   INTEGER,
    MEMBER_ID INTEGER,
    BOOK_NAME VARCHAR(200),
    RETURN_DATE  DATE,
    PRIMARY KEY(RETURN_ID)
);

CREATE TABLE BOOK_DETAIL( 
    BOOK_ID      INTEGER,
    MEMBER_ID    INTEGER,
    BOOK_NAME    VARCHAR(200),
    MEMBER_NAME  VARCHAR(200),
    BORROW_DATE  DATE,
    RETURN_DATE  DATE,
    PRIMARY KEY(MEMBER_ID, BOOK_ID)
);


-- Insert data into MEMBERS table
INSERT INTO MEMBERS
  VALUES ( 101,'Nur', 'YILMAZ', '123', 'staff');

INSERT INTO MEMBERS
  VALUES ( 102, 'R�meysa', 'KAYA', '123','staff');



-- Insert data into BOOKS table
INSERT INTO BOOKS
  VALUES (1,'The Alchemist', 'Fiction', 'Paulo Coelho');

INSERT INTO BOOKS
  VALUES (2, 'The Hitchhikers Guide to the Galaxy', 'Science Fiction', 'Douglas Adams');

INSERT INTO BOOKS
  VALUES (3, 'The Lord of the Rings', 'Fantasy', 'J.R.R. Tolkien');

INSERT INTO BOOKS
  VALUES (4, 'The Girl with the Dragon Tattoo', 'Thriller', 'Stieg Larsson');


ALTER TABLE BORROW_BOOK ADD CONSTRAINT FK_BORROW_BOOK_BOOKS FOREIGN KEY(BORROW_ID) REFERENCES BOOKS(BOOK_ID)
ALTER TABLE BORROW_BOOK ADD CONSTRAINT FK_BORROW_BOOK_MEMBERS FOREIGN KEY(BORROW_ID) REFERENCES MEMBERS(MEMBER_ID)
ALTER TABLE RETURN_BOOK ADD CONSTRAINT FK_RETURN_BOOK_BOOKS FOREIGN KEY(RETURN_ID) REFERENCES BOOKS(BOOK_ID)
ALTER TABLE RETURN_BOOK ADD CONSTRAINT FK_RETURN_BOOK_MEMBERS FOREIGN KEY(RETURN_ID) REFERENCES MEMBERS(MEMBER_ID)

ALTER TABLE BOOK_DETAIL ADD CONSTRAINT FK_BOOK_DETAIL_BOOKS FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID)
ALTER TABLE BOOK_DETAIL ADD CONSTRAINT FK_BOOK_DETAIL_MEMBERS FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)


  SELECT * FROM MEMBERS;
  
  SELECT * FROM BOOKS;

  SELECT * FROM BORROW_BOOK;

  SELECT * FROM RETURN_BOOK;

  SELECT * FROM BOOK_DETAIL;

  --DROP TABLE BOOKS, BOOK_DETAIL,BORROW_BOOK, MEMBERS, RETURN_BOOK;


  --DELETE FROM BOOK_DETAIL;
